# Generated by Django 3.2.7 on 2022-05-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_street1', models.CharField(max_length=100)),
                ('from_street2', models.CharField(max_length=100)),
                ('from_city', models.CharField(max_length=100)),
                ('from_state', models.CharField(max_length=3)),
                ('from_zip', models.CharField(max_length=10)),
                ('from_country', models.CharField(max_length=20)),
                ('from_phone', models.CharField(max_length=20)),
                ('to_street1', models.CharField(max_length=100)),
                ('to_street2', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('to_state', models.CharField(max_length=3)),
                ('to_zip', models.CharField(max_length=10)),
                ('to_country', models.CharField(max_length=20)),
                ('to_phone', models.CharField(max_length=20)),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
            ],
        ),
    ]
